import { and, eq } from "drizzle-orm";
import { assets, backtestNavs, backtestPositions, backtestRuns, backtestTrades, dailyBars, dataVersions, marketRuleSets, strategies, strategyVersions, users } from "../drizzle/schema.ts";
import { getDb } from "../server/db.ts";
import { runDailyBacktest } from "../server/quant/backtest.ts";
import { DEFAULT_MARKET_RULES } from "../server/quant/marketRules.ts";

const DATA_VERSION_ID = 90002, INITIAL_CAPITAL = 1_000_000, SYMBOL = "510300.SH", VOL_WINDOW = 20, VOL_THRESHOLD = 0.25;
const asDate = value => new Date(`${value}T00:00:00.000Z`), dateKey = value => new Date(value).toISOString().slice(0, 10);
const weekKey = value => { const d = asDate(value); d.setUTCDate(d.getUTCDate() - ((d.getUTCDay() + 6) % 7)); return dateKey(d); };
const standardDeviation = xs => { const m = xs.reduce((sum, x) => sum + x, 0) / xs.length; return Math.sqrt(xs.reduce((sum, x) => sum + (x - m) ** 2, 0) / Math.max(1, xs.length - 1)); };
const db = await getDb(); if (!db) throw new Error("研究数据库暂不可用。");
const owner = process.env.OWNER_OPEN_ID ? (await db.select().from(users).where(eq(users.openId, process.env.OWNER_OPEN_ID)).limit(1))[0] : (await db.select().from(users).where(eq(users.role, "admin")).limit(1))[0]; if (!owner) throw new Error("未找到项目管理员。");
const version = (await db.select().from(dataVersions).where(eq(dataVersions.id, DATA_VERSION_ID)).limit(1))[0]; if (!version || version.qualityStatus !== "passed") throw new Error("目标数据版本未通过质量检查。");
const raw = await db.select({ assetId: assets.id, symbol: assets.symbol, tradeDate: dailyBars.tradeDate, open: dailyBars.open, high: dailyBars.high, low: dailyBars.low, close: dailyBars.close, preClose: dailyBars.preClose, volume: dailyBars.volume, amount: dailyBars.amount }).from(dailyBars).innerJoin(assets, eq(dailyBars.assetId, assets.id)).where(eq(dailyBars.versionId, DATA_VERSION_ID));
const bars = raw.filter(row => row.symbol === SYMBOL).map(row => ({ assetId: row.assetId, symbol: row.symbol, tradeDate: dateKey(row.tradeDate), open: Number(row.open), high: Number(row.high), low: Number(row.low), close: Number(row.close), preClose: row.preClose === null ? undefined : Number(row.preClose), volume: row.volume === null ? undefined : Number(row.volume), amount: row.amount === null ? undefined : Number(row.amount) })).sort((a, b) => a.tradeDate.localeCompare(b.tradeDate));
const weeklyLast = new Map(); bars.forEach((bar, index) => weeklyLast.set(weekKey(bar.tradeDate), index)); const targets = {}, rebalanceDates = [];
for (const signalIndex of weeklyLast.values()) { const execution = bars[signalIndex + 1]; if (!execution || signalIndex < VOL_WINDOW) continue; const returns = bars.slice(signalIndex - VOL_WINDOW + 1, signalIndex + 1).map((bar, index, list) => index ? bar.close / list[index - 1].close - 1 : 0).slice(1); const annualizedVol = standardDeviation(returns) * Math.sqrt(252); targets[execution.tradeDate] = { [SYMBOL]: annualizedVol > VOL_THRESHOLD ? 0.5 : 1 }; rebalanceDates.push(execution.tradeDate); }
const strictRule = { ...DEFAULT_MARKET_RULES.CN, sellTaxRate: 0, priceLimitPct: null, notes: "ETF研究严格口径：T+1、100份整手、0.03%佣金（最低5元）、8bp滑点；国内ETF卖出不计股票印花税。" }; const baselineRule = { ...strictRule, commissionRate: 0, minimumCommission: 0, slippageBps: 0, settlementLagDays: 0, lotSize: 1 };
const input = { bars, rebalanceDates, targetWeights: {}, targetWeightsByDate: targets, initialCapital: INITIAL_CAPITAL }; const baseline = runDailyBacktest({ ...input, rule: baselineRule, strict: false }); const strict = runDailyBacktest({ ...input, rule: strictRule, strict: true });
const strategy = (await db.select().from(strategies).where(eq(strategies.slug, "market-regime-overlay")).limit(1))[0]; const strategyVersion = strategy ? (await db.select().from(strategyVersions).where(and(eq(strategyVersions.strategyId, strategy.id), eq(strategyVersions.version, 1))).limit(1))[0] : null; const ruleSet = (await db.select().from(marketRuleSets).where(and(eq(marketRuleSets.market, "CN"), eq(marketRuleSets.active, true))).limit(1))[0]; if (!strategyVersion || !ruleSet) throw new Error("策略模板或A股规则集尚未初始化。");
const assetId = bars[0]?.assetId; async function save(mode, result, rule) { const now = new Date(); const inserted = await db.insert(backtestRuns).values({ strategyVersionId: strategyVersion.id, ruleSetId: ruleSet.id, mode, status: "completed", startDate: asDate(bars[0].tradeDate), endDate: asDate(bars.at(-1).tradeDate), dataVersionIds: [DATA_VERSION_ID], configSnapshot: { template: "market_regime_overlay", symbol: SYMBOL, volatilityWindow: VOL_WINDOW, annualizedVolatilityThreshold: VOL_THRESHOLD, weeklySignalAtClose: true, executionOnNextTradingOpen: true, strictRule: rule, rebalances: rebalanceDates.length }, qualityResult: version.qualityReport, metrics: result.metrics, createdBy: owner.id, startedAt: now, finishedAt: new Date() }); const runId = Number(inserted[0].insertId); for (let start = 0; start < result.nav.length; start += 500) await db.insert(backtestNavs).values(result.nav.slice(start, start + 500).map(point => ({ runId, tradeDate: asDate(point.tradeDate), nav: String(point.nav), dailyReturn: String(point.dailyReturn), exposure: String(point.exposure), turnover: String(point.turnover) }))); for (let start = 0; start < result.trades.length; start += 500) await db.insert(backtestTrades).values(result.trades.slice(start, start + 500).map(trade => ({ runId, assetId, tradeDate: asDate(trade.tradeDate), side: trade.side, quantity: String(trade.quantity), price: String(trade.price), commission: String(trade.commission), taxes: String(trade.taxes), slippage: String(trade.slippage), status: trade.status, rejectionReason: trade.rejectionReason ?? null }))); for (let start = 0; start < result.positions.length; start += 500) await db.insert(backtestPositions).values(result.positions.slice(start, start + 500).map(position => ({ runId, assetId, tradeDate: asDate(position.tradeDate), quantity: String(position.quantity), marketValue: String(position.marketValue), weight: String(position.weight) }))); return runId; }
const baselineRunId = await save("baseline", baseline, baselineRule), strictRunId = await save("strict", strict, strictRule); console.log(JSON.stringify({ dataVersionId: DATA_VERSION_ID, period: { start: bars[0].tradeDate, end: bars.at(-1).tradeDate }, symbol: SYMBOL, signalRule: { volatilityWindow: VOL_WINDOW, annualizedVolatilityThreshold: VOL_THRESHOLD, signalToExecution: "至少一个交易时点" }, rebalances: rebalanceDates.length, baseline: { runId: baselineRunId, metrics: baseline.metrics, trades: baseline.trades.length }, strict: { runId: strictRunId, metrics: strict.metrics, trades: strict.trades.length, rejectedTrades: strict.trades.filter(trade => trade.status === "rejected").length } }, null, 2)); process.exit(0);
