import { readFile } from "node:fs/promises";
import { and, eq } from "drizzle-orm";
import { assets, backtestNavs, backtestPositions, backtestRuns, backtestTrades, dailyBars, dataVersions, marketRuleSets, strategies, strategyVersions, users } from "../drizzle/schema.ts";
import { getDb } from "../server/db.ts";
import { runDailyBacktest } from "../server/quant/backtest.ts";
import { DEFAULT_MARKET_RULES } from "../server/quant/marketRules.ts";

const DATA_VERSION_ID = 360002;
const INITIAL_CAPITAL = 1_000_000;
const selection = JSON.parse(await readFile(new URL("../research_outputs_cn_quality_value_pit_selection.json", import.meta.url), "utf8"));
const dateKey = value => new Date(value).toISOString().slice(0, 10);
const asDate = value => new Date(`${value}T00:00:00.000Z`);
const normalizedDate = value => { const raw = String(value); return /^\d{8}$/.test(raw) ? `${raw.slice(0, 4)}-${raw.slice(4, 6)}-${raw.slice(6, 8)}` : raw; };
const db = await getDb();
if (!db) throw new Error("研究数据库暂不可用。");
const owner = process.env.OWNER_OPEN_ID ? (await db.select().from(users).where(eq(users.openId, process.env.OWNER_OPEN_ID)).limit(1))[0] : (await db.select().from(users).where(eq(users.role, "admin")).limit(1))[0];
if (!owner) throw new Error("未找到项目管理员账户。");
const sourceVersion = (await db.select().from(dataVersions).where(eq(dataVersions.id, DATA_VERSION_ID)).limit(1))[0];
if (!sourceVersion || sourceVersion.qualityStatus !== "passed") throw new Error("质量价值复权价格版本不存在或未通过质量检查。");
const rows = await db.select({ assetId: assets.id, symbol: assets.symbol, tradeDate: dailyBars.tradeDate, open: dailyBars.open, high: dailyBars.high, low: dailyBars.low, close: dailyBars.close, preClose: dailyBars.preClose, volume: dailyBars.volume, amount: dailyBars.amount }).from(dailyBars).innerJoin(assets, eq(dailyBars.assetId, assets.id)).where(eq(dailyBars.versionId, DATA_VERSION_ID));
const selectedSymbols = [...new Set(selection.selections.flatMap(snapshot => snapshot.selected.map(item => item.symbol)))];
const bars = rows.map(row => ({ symbol: row.symbol, tradeDate: dateKey(row.tradeDate), open: Number(row.open), high: Number(row.high), low: Number(row.low), close: Number(row.close), preClose: row.preClose === null ? undefined : Number(row.preClose), volume: row.volume === null ? undefined : Number(row.volume), amount: row.amount === null ? undefined : Number(row.amount) })).filter(row => selectedSymbols.includes(row.symbol));
const calendar = [...new Set(bars.map(row => row.tradeDate))].sort();
const targetWeightsByDate = Object.fromEntries(selection.selections.map(snapshot => [normalizedDate(snapshot.executionDate), Object.fromEntries(snapshot.selected.map(item => [item.symbol, 1 / snapshot.selected.length]))]));
const rebalances = Object.keys(targetWeightsByDate).filter(date => calendar.includes(date));
if (rebalances.length !== selection.selections.length) throw new Error(`公告日后执行日期不在复权价格版本中：${JSON.stringify({ requested: Object.keys(targetWeightsByDate), available: rebalances, firstCalendarDate: calendar[0], lastCalendarDate: calendar.at(-1) })}`);
const strictRule = { ...DEFAULT_MARKET_RULES.CN, priceLimitPct: 0.1, notes: "质量价值股票研究严格口径：非金融主板候选；T+1、100股整手、0.03%佣金（最低5元）、8bp滑点、卖出印花税0.1%。未建模历史ST特别涨跌幅，故结果仅为候选复现。" };
const baselineRule = { ...strictRule, commissionRate: 0, minimumCommission: 0, slippageBps: 0, settlementLagDays: 0, lotSize: 1, sellTaxRate: 0 };
const base = { bars, rebalanceDates: rebalances, targetWeights: {}, targetWeightsByDate, initialCapital: INITIAL_CAPITAL };
const baseline = runDailyBacktest({ ...base, rule: baselineRule, strict: false });
const strict = runDailyBacktest({ ...base, rule: strictRule, strict: true });
const strategy = (await db.select().from(strategies).where(eq(strategies.slug, "ebit-ev-quality-value")).limit(1))[0];
const strategyVersion = strategy ? (await db.select().from(strategyVersions).where(and(eq(strategyVersions.strategyId, strategy.id), eq(strategyVersions.version, 1))).limit(1))[0] : null;
const ruleSet = (await db.select().from(marketRuleSets).where(and(eq(marketRuleSets.market, "CN"), eq(marketRuleSets.active, true))).limit(1))[0];
if (!strategyVersion || !ruleSet) throw new Error("质量价值策略模板或A股规则集尚未初始化。");
const assetIds = new Map(rows.map(row => [row.symbol, row.assetId]));
async function save(mode, result, rule) {
  const now = new Date();
  const inserted = await db.insert(backtestRuns).values({ strategyVersionId: strategyVersion.id, ruleSetId: ruleSet.id, mode, status: "completed", startDate: asDate(calendar[0]), endDate: asDate(calendar.at(-1)), dataVersionIds: [DATA_VERSION_ID], configSnapshot: { template: "ebit_ev_quality", selectionArtifact: "research_outputs_cn_quality_value_pit_selection.json", factorFormula: selection.formula, annualSignalDates: selection.selections.map(snapshot => snapshot.signalDate), executionDates: rebalances, holdingsPerRebalance: 10, equalWeight: true, eligibility: "非金融主板、历史总市值至少300亿元、EBIT为正、Gross Profitability为正", strictRule: rule }, qualityResult: sourceVersion.qualityReport, metrics: result.metrics, createdBy: owner.id, startedAt: now, finishedAt: new Date() });
  const runId = Number(inserted[0].insertId);
  for (let index = 0; index < result.nav.length; index += 500) await db.insert(backtestNavs).values(result.nav.slice(index, index + 500).map(point => ({ runId, tradeDate: asDate(point.tradeDate), nav: String(point.nav), dailyReturn: String(point.dailyReturn), exposure: String(point.exposure), turnover: String(point.turnover) })));
  const trades = result.trades.map(trade => ({ ...trade, assetId: assetIds.get(trade.symbol) })).filter(trade => trade.assetId); for (let index = 0; index < trades.length; index += 500) await db.insert(backtestTrades).values(trades.slice(index, index + 500).map(trade => ({ runId, assetId: trade.assetId, tradeDate: asDate(trade.tradeDate), side: trade.side, quantity: String(trade.quantity), price: String(trade.price), commission: String(trade.commission), taxes: String(trade.taxes), slippage: String(trade.slippage), status: trade.status, rejectionReason: trade.rejectionReason ?? null })));
  const positions = result.positions.map(position => ({ ...position, assetId: assetIds.get(position.symbol) })).filter(position => position.assetId); for (let index = 0; index < positions.length; index += 500) await db.insert(backtestPositions).values(positions.slice(index, index + 500).map(position => ({ runId, assetId: position.assetId, tradeDate: asDate(position.tradeDate), quantity: String(position.quantity), marketValue: String(position.marketValue), weight: String(position.weight) })));
  return runId;
}
const baselineRunId = await save("baseline", baseline, baselineRule);
const strictRunId = await save("strict", strict, strictRule);
console.log(JSON.stringify({ dataVersionId: DATA_VERSION_ID, period: { start: calendar[0], end: calendar.at(-1) }, rebalances, candidateCounts: selection.selections.map(snapshot => ({ fiscalPeriod: snapshot.fiscalPeriod, candidateCount: snapshot.candidateCount, selectedCount: snapshot.selected.length })), baseline: { runId: baselineRunId, metrics: baseline.metrics, trades: baseline.trades.length }, strict: { runId: strictRunId, metrics: strict.metrics, trades: strict.trades.length, rejectedTrades: strict.trades.filter(trade => trade.status === "rejected").length } }, null, 2));
process.exit(0);
