import type { Express, Request, Response } from "express";
import multer from "multer";
import Papa from "papaparse";
import parquet from "parquetjs-lite";
import { storagePut } from "../storage";
import { sdk } from "../_core/sdk";
import { hasResearchAccess, persistBars } from "./service";
import { toDateKey } from "./quality";
import type { AssetType, CanonicalBar, Market } from "./types";

const upload = multer({ storage: multer.memoryStorage(), limits: { fileSize: 45 * 1024 * 1024 } });
export const aliases: Record<string, string[]> = { symbol: ["symbol", "ts_code", "ticker", "code"], tradeDate: ["trade_date", "tradeDate", "date"], open: ["open"], high: ["high"], low: ["low"], close: ["close"], preClose: ["pre_close", "preClose"], volume: ["vol", "volume"], amount: ["amount", "turnover"] };
function field(row: Record<string, unknown>, key: string) { const found = aliases[key].find(alias => Object.prototype.hasOwnProperty.call(row, alias)); return found ? row[found] : undefined; }
export function normalizeImportedBars(rows: Record<string, unknown>[]): CanonicalBar[] { return rows.map(row => ({ symbol: String(field(row, "symbol") ?? "").trim(), tradeDate: toDateKey(String(field(row, "tradeDate") ?? "")), open: Number(field(row, "open")), high: Number(field(row, "high")), low: Number(field(row, "low")), close: Number(field(row, "close")), preClose: field(row, "preClose") === undefined ? null : Number(field(row, "preClose")), volume: field(row, "volume") === undefined ? null : Number(field(row, "volume")), amount: field(row, "amount") === undefined ? null : Number(field(row, "amount")) })); }
export function resolveFieldMapping(rows: Record<string, unknown>[]) { return Object.fromEntries(Object.entries(aliases).map(([canonical, candidates]) => [canonical, candidates.find(candidate => rows.some(row => Object.prototype.hasOwnProperty.call(row, candidate))) ?? null])); }
async function parseFile(file: Express.Multer.File) { if (file.originalname.toLowerCase().endsWith(".parquet")) { const reader = await parquet.ParquetReader.openBuffer(file.buffer); const cursor = reader.getCursor(); const rows: Record<string, unknown>[] = []; let record: Record<string, unknown> | null; while ((record = await cursor.next())) rows.push(record); await reader.close(); return rows; } return Papa.parse<Record<string, unknown>>(file.buffer.toString("utf-8"), { header: true, skipEmptyLines: true }).data; }
export function registerImportRoute(app: Express) { app.post("/api/import/daily-bars", upload.single("file"), async (req: Request, res: Response) => { try { const user = await sdk.authenticateRequest(req); if (!user || user.isCron || !(await hasResearchAccess(user.id, user.role === "admin"))) return res.status(403).json({ error: "仅限已授权成员导入研究数据。" }); if (!req.file) return res.status(400).json({ error: "请选择CSV或Parquet文件。" }); const rows = await parseFile(req.file); const key = `research-imports/${user.id}/${Date.now()}-${req.file.originalname}`; const stored = await storagePut(key, req.file.buffer, req.file.mimetype || "application/octet-stream"); const fieldMapping = resolveFieldMapping(rows); const result = await persistBars(user.id, `上传文件 · ${req.file.originalname}`, req.body.market as Market, req.body.exchange || "IMPORT", req.body.currency || "USD", req.body.assetType as AssetType, normalizeImportedBars(rows), stored.key, { originalName: req.file.originalname, mimeType: req.file.mimetype, fieldMapping }); res.json({ version: result.version, report: result.report }); } catch (error) { res.status(500).json({ error: error instanceof Error ? error.message : "导入失败" }); } }); }
